// This file was autogenerated by C:\Users\surfing\Desktop\yguan-Hack_Day_JS_Projects-c7298ec\closure\depswriter.py.
// Please do not edit.
goog.addDependency('CircularMenu/js/CircularMenu.js', ['hackday.CircularMenu'], []);
goog.addDependency('CircularMenu/js/CircularMenuDemo.js', ['hackday.CircularMenuDemo'], ['hackday.CircularMenu.HowllowPie', 'hackday.CircularMenu.data.pie', 'hackday.CircularMenu.data.smallPie']);
goog.addDependency('CircularMenu/js/HollowPie.js', ['hackday.CircularMenu.HowllowPie'], []);
goog.addDependency('CircularMenu/js/data/pie.js', ['hackday.CircularMenu.data.pie'], []);
goog.addDependency('CircularMenu/js/data/smallPie.js', ['hackday.CircularMenu.data.smallPie'], []);
goog.addDependency('EvaluationMatrix/js/EvaluationMatrix.js', ['hackday.EvaluationMatrix'], ['hackday.KeyEditTableHelper']);
goog.addDependency('EvaluationMatrix/js/EvaluationMatrixConfiguration.js', ['hackday.EvaluationMatrix.ConfigurationComponent'], []);
goog.addDependency('EvaluationMatrix/js/EvaluationMatrixSetup.js', ['hackday.EvaluationMatrixSetup'], ['KeyTableModule', 'hackday.EvaluationMatrix', 'hackday.EvaluationMatrix.ConfigurationComponent', 'jquery.collapsible']);
goog.addDependency('EvaluationMatrix/js/KeyEditTableHelper.js', ['hackday.KeyEditTableHelper'], []);
goog.addDependency('InteractiveCanvas/js/data/shapes.js', ['hackday.interactiveCanvas.data.shapes'], []);
goog.addDependency('InteractiveCanvas/js/data/us-states.js', ['hackday.interactiveCanvas.data.states'], []);
goog.addDependency('InteractiveCanvas/js/data/world.js', ['hackday.interactiveCanvas.data.world'], []);
goog.addDependency('InteractiveCanvas/js/map.js', ['hackday.interactiveCanvas.map'], ['paper']);
goog.addDependency('InteractiveCanvas/js/shapeMaker.js', ['hackday.interactiveCanvas.shapeMaker'], ['paper']);
goog.addDependency('common/js/ColVis.js', ['ColVis'], []);
goog.addDependency('common/js/KeyTable.js', ['KeyTable'], []);
goog.addDependency('common/js/KeyTableModule.js', ['KeyTableModule'], ['ColVis', 'KeyTable', 'TableTools', 'jquery.dataTables', 'jquery.jeditable']);
goog.addDependency('common/js/TableTools.js', ['TableTools'], []);
goog.addDependency('common/js/jquery.collapsible.js', ['jquery.collapsible'], []);
goog.addDependency('common/js/jquery.dataTables.js', ['jquery.dataTables'], []);
goog.addDependency('common/js/jquery.jeditable.js', ['jquery.jeditable'], []);
goog.addDependency('common/js/paper.js', ['paper'], []);
